[DONE] Cell editable by clicking and do ajax by press return key
If enconter error 'table.js:8 Uncaught TypeError: $.ajax is not a function' but you can use in another page. Please double-check if you're using full-version of jquery and not some slim version.

Using the jquery cdn-script link that comes with jquery. The problem is this one by default is slim.jquery.js which doesn't have the ajax function in it. So, if you're using (copy-pasted from Bootstrap website) slim version jquery script link, use the full version instead.

That is to say use <script src="https://code.jquery.com/jquery-3.1.1.min.js"> instead of <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"